apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k8s-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: project-k8s
  template:
    metadata:
      labels:
        app: project-k8s
    spec:
      containers:
      - name: project-k8s
        image: techiepawan/project-k8s:latest
        ports:
        - containerPort: 8080  # Corrected indentation here
      
---
apiVersion: v1
kind: Service
metadata:
  name: project-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: project-k8s
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
